import { BlockToComponentModel } from '../types/types';
import {
  BusyRoutesBlock,
  DowloadAppBlock,
  FaqBlock,
  MagBlock,
  PrepositionBlock,
  RichTextBlock,
  SeoBlock,
  SuppliersBlock,
  SupportBodyBlock,
  SupportFooterBlock,
  supportHeaderBlock,
  VisaConditionsBlock,
  VisaDescriptionBlock,
  VisaExplanationBlock,
  VisaGuidanceIMageBlock,
  VisaLandingHeroBlock,
  VisaPageHeroBlock,
  VisaPriceInfoBlock,
  VisaPriceTableBlock,
  VisaValidityPeriodBlock,
} from './share';

export const cmsBlockToComponentMapper: BlockToComponentModel = {
  'blocks.preposition': PrepositionBlock,
  'blocks.faq': FaqBlock,
  'blocks.app-download': DowloadAppBlock,
  'blocks.supplier': SuppliersBlock,
  'blocks.rich-text': RichTextBlock,
  'blocks.busy-route': BusyRoutesBlock,
  'blocks.mag': MagBlock,
  'blocks.seo': SeoBlock,
  'blocks.support-header': supportHeaderBlock,
  'blocks.support-body': SupportBodyBlock,
  'blocks.support-footer': SupportFooterBlock,
  'blocks.visa-hero': VisaLandingHeroBlock,
  'blocks.visa-table': VisaPriceTableBlock,
  'blocks.visa-conditions': VisaConditionsBlock,
  'blocks.visa-description': VisaDescriptionBlock,
  'blocks.visa-explanation': VisaExplanationBlock,
  'blocks.visa-price-info': VisaPriceInfoBlock,
  'blocks.visa-page-hero': VisaPageHeroBlock,
  'blocks.visa-validity-period': VisaValidityPeriodBlock,
  'blocks.visa-guidance-image': VisaGuidanceIMageBlock,
  'blocks.reusable-block-reference': null,
};
