import { FC } from 'react';
import { CmsFaqProps } from '../components/faq/types';
import { PrepositionProps } from '../components/preposition/types';
import { DownloadProps } from '../components/downloadApp/types';
import { SuppliersProps } from '../components/suppliers/types';
import { RichTextPropsType } from '../components/richText/types';
import { BusyRoutesProps } from '../components/busyRoutes/types';
import { MagProps } from '../components/mag/types';
import { MetaSeoProps } from '../components/seo/type';
import { SupportHeaderProps } from '../components/support/header/types';
import { SupportBodyProps } from '../components/support/body/types';
import { SupportFooterProps } from '../components/support/footer/types';
import { VisaPriceTableProps } from '../components/visa/visaPriceTable/types';
import { VisaLandingHeroProps } from '../components/visa/visaLandingHero/types';
import { VisaConditionsProps } from '../components/visa/visaConditions/types';
import { VisaDescriptionProps } from '../components/visa/visaDescription/types';
import { VisaExplanationProps } from '../components/visa/visaExplanation/types';
import { VisaPriceInfoProps } from '../components/visa/visaPriceInfo/types';
import { VisaPageHeroProps } from '../components/visa/visaPageHero/types';
import { VisaValidityPeriodProps } from '../components/visa/visaValidityPeriod/types';
import { VisaGuidanceImageProps } from '../components/visa/visaGuidanceImage/types';

export type BlockToComponentModel = {
  'blocks.preposition': FC<PrepositionProps>;
  'blocks.faq': FC<CmsFaqProps>;
  'blocks.app-download': FC<DownloadProps>;
  'blocks.supplier': FC<SuppliersProps>;
  'blocks.rich-text': FC<RichTextPropsType>;
  'blocks.busy-route': FC<BusyRoutesProps>;
  'blocks.mag': FC<MagProps>;
  'blocks.seo': FC<MetaSeoProps>;
  'blocks.support-header': FC<SupportHeaderProps>;
  'blocks.support-body': FC<SupportBodyProps>;
  'blocks.support-footer': FC<SupportFooterProps>;
  'blocks.visa-hero': FC<VisaLandingHeroProps>;
  'blocks.visa-table': FC<VisaPriceTableProps>;
  'blocks.visa-conditions': FC<VisaConditionsProps>;
  'blocks.visa-description': FC<VisaDescriptionProps>;
  'blocks.visa-explanation': FC<VisaExplanationProps>;
  'blocks.visa-price-info': FC<VisaPriceInfoProps>;
  'blocks.visa-page-hero': FC<VisaPageHeroProps>;
  'blocks.visa-validity-period': FC<VisaValidityPeriodProps>;
  'blocks.visa-guidance-image': FC<VisaGuidanceImageProps>;
  'blocks.reusable-block-reference': FC | null;
};
