/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/admin/frequentcities": {
    post: operations["Train_AddFrequentCity"];
  };
  "/v1/admin/frequentcities/{id}": {
    delete: operations["Train_DeleteFrequentCity"];
  };
  "/v1/admin/order": {
    post: operations["Admin_AdminGetOrders"];
  };
  "/v1/admin/order/{orderId}": {
    get: operations["Admin_AdminGetOrder"];
  };
  "/v1/admin/order/{orderId}/passengers": {
    get: operations["Admin_AdminGetPassengers"];
  };
  "/v1/admin/order/{orderId}/payment": {
    get: operations["Admin_AdminGetPayment"];
  };
  "/v1/admin/order/{orderId}/status/{status}/ticket": {
    get: operations["Train_GetTicket"];
  };
  "/v1/admin/order/{orderId}/trains": {
    get: operations["Admin_AdminGetTrains"];
  };
  "/v1/admin/order_status": {
    get: operations["Admin_AdminGetOrderStatus"];
  };
  "/v1/admin/orders/{orderId}/trains/{trainId}/calculate-refund-penalty": {
    post: operations["Admin_AdminCalculateRefundPenalty"];
  };
  "/v1/admin/orders/{orderId}/trains/{trainId}/refund": {
    post: operations["Admin_AdminSubmitRefund"];
  };
  "/v1/admin/provider_names": {
    get: operations["Admin_AdminGetProviderNames"];
  };
  "/v1/admin/refund_requests": {
    post: operations["Admin_AdminRRList"];
  };
  "/v1/admin/refund_status": {
    get: operations["Admin_AdminGetRRStatus"];
  };
  "/v1/admin/ticketpdf/{orderId}": {
    get: operations["Admin_AdminGetTicketsPdf"];
  };
  "/v1/alert": {
    get: operations["Train_GetAlert"];
    post: operations["Train_CreateAlert"];
    patch: operations["Train_UpdateAlert"];
  };
  "/v1/calendar": {
    get: operations["Train_GetCalenderData"];
  };
  "/v1/captcha/verify": {
    post: operations["Train_VerifyCaptcha"];
  };
  "/v1/captcha/{orderId}": {
    get: operations["Train_GetCaptcha"];
  };
  "/v1/errors/{errorCode}": {
    get: operations["Train_GetError"];
  };
  "/v1/frequentcities": {
    get: operations["Train_GetFrequentCities"];
  };
  "/v1/orders": {
    get: operations["Train_GetOrders"];
    post: operations["Train_CreateOrder"];
  };
  "/v1/orders/{orderId}": {
    get: operations["Train_GetOrder"];
  };
  "/v1/orders/{orderId}/addpassengers": {
    post: operations["Train_AddPassengers"];
  };
  "/v1/orders/{orderId}/contactinfo": {
    post: operations["Train_UpdateContactInfo"];
  };
  "/v1/orders/{orderId}/createpayment": {
    post: operations["Train_CreatePayment"];
  };
  "/v1/orders/{orderId}/passenger-services": {
    post: operations["Train_SetPassengersOptionalService"];
  };
  "/v1/orders/{orderId}/reserve": {
    post: operations["Train_Reserve"];
  };
  "/v1/orders/{orderId}/trains/{trainId}/calculate-refund-penalty": {
    post: operations["Train_CalculateRefundPenalty"];
  };
  "/v1/orders/{orderId}/trains/{trainId}/passenger-services": {
    post: operations["Train_SetPassengersOptionalServicePerLeg"];
  };
  "/v1/orders/{orderId}/trains/{trainId}/refund": {
    get: operations["Train_Refund"];
  };
  "/v1/orders/{orderId}/trains/{trainId}/refund-actions": {
    post: operations["Train_SubmitRefund"];
  };
  "/v1/session": {
    post: operations["Session_GetSession"];
  };
  "/v1/stations": {
    get: operations["Train_GetStations"];
  };
  "/v1/stations/all": {
    get: operations["Train_GetAllStations"];
  };
  "/v1/ticketpdf/{orderId}": {
    get: operations["Train_GetTicketsPdf"];
  };
  "/v1/trains/list": {
    post: operations["Train_GetTrainList"];
  };
  "/v1/trains/{trainId}/freeoptionalservices": {
    get: operations["Train_GetFreeOptionalServices"];
  };
  "/v1/trains/{trainId}/intermediatestations": {
    get: operations["Train_GetIntermediateStations"];
  };
  "/v1/trains/{trainId}/optionalservices": {
    get: operations["Train_GetOptionalServices"];
  };
  "/v1/trains/{trainId}/price-detail": {
    post: operations["Train_GetPriceDetail"];
  };
  "/v2/orders/{orderId}": {
    get: operations["Train_GetOrderV2"];
  };
  "/v2/orders/{orderId}/createpayment": {
    post: operations["Train_CreatePaymentWithCaptcha"];
  };
}

export interface definitions {
  AdminAdminCalculateRefundPenaltyBody: {
    ticketIds?: string[];
  };
  AdminAdminSubmitRefundBody: {
    ticketIds?: string[];
  };
  TrainAddPassengersBody: {
    passengerIds?: string[];
  };
  TrainCalculateRefundPenaltyBody: {
    ticketIds?: string[];
  };
  TrainCreatePaymentBody: { [key: string]: unknown };
  TrainCreatePaymentWithCaptchaBody: {
    /** Format: int64 */
    captchaId?: string;
    captchaText?: string;
  };
  TrainGetPriceDetailBody: {
    passenger?: definitions["rajaPassengerCount"];
    wantCompartment?: boolean;
  };
  TrainReserveBody: { [key: string]: unknown };
  TrainSetPassengersOptionalServiceBody: {
    legs?: definitions["rajaSelectedOptionalServicePerLeg"][];
  };
  TrainSetPassengersOptionalServicePerLegBody: {
    selectedOptionalServices?: definitions["rajaSelectedOptionalService"][];
  };
  TrainSubmitRefundBody: {
    ticketIds?: string[];
  };
  TrainUpdateContactInfoBody: {
    phoneNumber?: string;
    email?: string;
  };
  /**
   * @default PERSIAN
   * @enum {string}
   */
  apirajaCalendarType: "PERSIAN" | "GREGORIAN";
  apirajaDateQuery: {
    /** Format: int64 */
    fromDate?: string;
    /** Format: int64 */
    tillDate?: string;
  };
  /**
   * @default GENDER_TYPE_UNDEFINED
   * @enum {string}
   */
  apirajaGenderType:
    | "GENDER_TYPE_UNDEFINED"
    | "GENDER_TYPE_FEMALE"
    | "GENDER_TYPE_MALE"
    | "Gender_TYPE_RATHER_NOT_SAY";
  apirajaInternalCountryObject: {
    countryNameEn?: string;
    countryNameFa?: string;
  };
  apirajaRefundResponse: {
    url?: string;
  };
  protobufAny: {
    "@type"?: string;
  } & { [key: string]: unknown };
  rajaAdminGetOrderResponse: {
    orderId?: string;
    orderNumber?: string;
    status?: definitions["rajaOrderStatus"];
    /** Format: int64 */
    issueDate?: string;
    userPhone?: string;
    /** Format: int64 */
    createdAt?: string;
  };
  rajaAdminGetOrdersRequest: {
    /** Format: int32 */
    pageNumber?: number;
    /** Format: int32 */
    pageLimit?: number;
    moveDate?: definitions["apirajaDateQuery"];
    orderNumber?: string;
    purchaseDate?: definitions["apirajaDateQuery"];
    trainNumber?: string;
    passengerPhoneNumber?: string;
    passengerNationalCode?: string;
    passengerName?: string;
    trackingId?: string;
    owner?: string;
    status?: definitions["rajaOrderStatus"];
    providerName?: string;
  };
  rajaAdminGetOrdersResponse: {
    orders?: definitions["rajaAdminOrders"][];
    /** Format: int64 */
    pages?: string;
    /** Format: int64 */
    count?: string;
  };
  rajaAdminGetPassengersResponse: {
    departure?: definitions["rajaTrainTicket"][];
    return?: definitions["rajaTrainTicket"][];
  };
  rajaAdminGetTrainsResponse: {
    trains?: definitions["rajaAdminTrainInfo"][];
  };
  rajaAdminOrders: {
    orderId?: string;
    orderNumber?: string;
    passengerPhoneNumber?: string;
    /** Format: int64 */
    issueDate?: string;
    trainNumber?: definitions["rajaStr"];
    moveDate?: definitions["rajaDate"];
    companyName?: definitions["rajaStr"];
    /** Format: int64 */
    passengerCount?: string;
    status?: definitions["rajaOrderStatus"];
    origin?: string;
    dest?: string;
    trainId?: definitions["rajaStr"];
    providerName?: definitions["rajaStr"];
    ticketNumber?: definitions["rajaStr"];
  };
  /** Get Refund List ------------------------------------- */
  rajaAdminRRRequest: {
    orderNumber?: string;
    saleNumber?: string;
    refundStatus?: definitions["rajaRefundStatus"];
    departureDate?: definitions["apirajaDateQuery"];
    refundDate?: definitions["apirajaDateQuery"];
    /** Format: int32 */
    pageNumber?: number;
    /** Format: int32 */
    pageLimit?: number;
    providerName?: string;
    userPhone?: string;
    ticketNumber?: string;
    nationalCode?: string;
    trainNumber?: string;
  };
  rajaAdminRRResponse: {
    list?: definitions["rajaAdminRefundDetails"][];
    /** Format: int64 */
    pages?: string;
    /** Format: int64 */
    count?: string;
  };
  rajaAdminRefundDetails: {
    orderId?: string;
    orderNumber?: string;
    userPhone?: string;
    userId?: string;
    refundStatus?: definitions["rajaRefundStatus"];
    /** Format: int64 */
    departureDate?: string;
    origin?: string;
    dest?: string;
    ticketNumber?: string;
    providerName?: string;
    /** Format: int64 */
    refundedDate?: string;
    refundAmount?: string;
    refundPenalty?: string;
    totalPrice?: string;
    firstName?: string;
    lastName?: string;
    englishFirstName?: string;
    englishLastName?: string;
    trainTitle?: string;
  };
  rajaAdminTrainInfo: {
    trainId?: string;
    originName?: string;
    destinationName?: string;
    trainNumber?: string;
    /** Format: int64 */
    departureDate?: string;
    wagonName?: string;
    providerName?: string;
  };
  /** Request message for creating and updatting alert data */
  rajaAlertRequest: {
    id?: string;
    isActive?: boolean;
    originCode?: string;
    destinationCode?: string;
    /** Format: int64 */
    departureDate?: string;
  };
  /** Response message for creatting alert data */
  rajaAlertResponse: {
    id?: string;
    message?: string;
  };
  rajaCalculateRefundPenaltyResponse: {
    orderId?: string;
    trainInfo?: definitions["rajaTrainInfo"];
    tickets?: definitions["rajaTrainTicket"][];
  };
  rajaCalenderData: {
    minimumPrice?: string;
    gregorianDepartureDate?: string;
    persianDepartureDate?: string;
  };
  /**
   * @default COMPARTMENT_GENDER_UNDEFINED
   * @enum {string}
   */
  rajaCompartmentGenderType:
    | "COMPARTMENT_GENDER_UNDEFINED"
    | "COMPARTMENT_GENDER_MEN_ONLY"
    | "COMPARTMENT_GENDER_WOMEN_ONLY"
    | "COMPARTMENT_GENDER_FAMILY";
  rajaCreateOrderRequest: {
    requestedTrain?: definitions["rajaRequestedTrain"][];
    passenger?: definitions["rajaPassengerCount"];
    compartmentGenderType?: definitions["rajaCompartmentGenderType"];
  };
  rajaCreateOrderResponse: {
    orderId?: string;
  };
  rajaCreatePaymentResponse: {
    paymentId?: string;
    /** Format: int64 */
    serviceCode?: string;
    provider?: string;
    /** Format: int64 */
    price?: string;
  };
  rajaDate: {
    /** Format: int64 */
    departure?: string;
    /** Format: int64 */
    return?: string;
  };
  rajaErrorCodeResponse: {
    errorMessage?: string;
  };
  rajaFrequentCity: {
    id?: string;
    code?: string;
    /** Format: int32 */
    rank?: number;
  };
  /** Response message for getting alert data */
  rajaGetAlertResponse: {
    id?: string;
    isActive?: boolean;
    originCode?: string;
    destinationCode?: string;
    /** Format: int64 */
    departureDate?: string;
    isModuleAvailable?: boolean;
  };
  rajaGetCalenderDataResponse: {
    calendarData?: definitions["rajaCalenderData"][];
  };
  rajaGetCaptchaResponse: {
    /** Format: int64 */
    captchaId?: string;
    /** Format: byte */
    image?: string;
    required?: boolean;
  };
  rajaGetFreeOptionalServicesResponse: {
    optionalServices?: definitions["rajaOptionalService"][];
  };
  rajaGetOptionalServicesResponse: {
    optionalServices?: definitions["rajaOptionalService"][];
  };
  rajaGetOrderResponse: {
    orderId?: string;
    orderNumber?: string;
    status?: definitions["rajaOrderStatus"];
    /** Format: int64 */
    reserveExpireDate?: string;
    userId?: string;
    /** Format: int64 */
    createdAt?: string;
    /** Format: uint64 */
    price?: string;
    trips?: definitions["rajaTrainTrip"][];
    isCaptchaRequired?: boolean;
  };
  rajaGetOrderStatusResponse: {
    status?: definitions["rajaOrderStatuses"][];
  };
  rajaGetOrdersResponse: {
    orders?: definitions["rajaGetOrderResponse"][];
  };
  rajaGetProviderNamesResponse: {
    provider?: string[];
  };
  /** Refund statuses ------------------------------------- */
  rajaGetRefundStatusResponse: {
    status?: definitions["rajaRefundStatuses"][];
  };
  rajaGetTicketPdfResponse: {
    url?: string;
  };
  rajaGetTrainListRequest: {
    queries?: definitions["rajaTrainListQuery"][];
  };
  rajaGetTrainListResponse: {
    trainLists?: definitions["rajaTrainList"][];
    /** Format: int64 */
    validUntil?: string;
    /** Format: int64 */
    validSeconds?: string;
  };
  rajaIntermediateStationsResponse: {
    stations?: definitions["rajaStation"][];
  };
  rajaOptionalService: {
    id?: string;
    name?: string;
    /** Format: uint64 */
    price?: string;
  };
  rajaOrderPayment: {
    rrn?: string;
    /** Format: int64 */
    paymentTime?: string;
    /** Format: uint64 */
    price?: string;
    status?: definitions["rajaPaymentStatus"];
    mask?: string;
    paymentType?: string;
  };
  /**
   * @default ORDER_STATUS_UNDEFINED
   * @enum {string}
   */
  rajaOrderStatus:
    | "ORDER_STATUS_UNDEFINED"
    | "ORDER_STATUS_ORDER_CREATED"
    | "ORDER_STATUS_ORDER_PASSENGERED"
    | "ORDER_STATUS_ORDER_RESERVED"
    | "ORDER_STATUS_RESERVATION_EXPIRED"
    | "ORDER_STATUS_PAYMENT_SUCCESS"
    | "ORDER_STATUS_BUY_FAILED"
    | "ORDER_STATUS_BUY_PENDING"
    | "ORDER_STATUS_BUY_CONFIRMED"
    | "ORDER_STATUS_BUY_PARTIALLED"
    | "ORDER_STATUS_RESERVE_FAILED";
  rajaOrderStatuses: {
    label?: string;
    value?: definitions["rajaOrderStatus"];
  };
  rajaPassenger: {
    firstName?: string;
    lastName?: string;
    nationalCode?: string;
    /** Format: int64 */
    birthDate?: string;
    genderType?: definitions["apirajaGenderType"];
    englishFirstName?: string;
    englishLastName?: string;
    passportId?: string;
    passportExpireDate?: string;
    isForeign?: boolean;
    passportCountryDetail?: definitions["apirajaInternalCountryObject"];
  };
  rajaPassengerCount: {
    /** Format: int64 */
    adult?: number;
    /** Format: int64 */
    child?: number;
    /** Format: int64 */
    infant?: number;
    /** Format: int64 */
    adultForeign?: number;
  };
  /**
   * @default PAYMENT_STATUS_UNDEFINED
   * @enum {string}
   */
  rajaPaymentStatus:
    | "PAYMENT_STATUS_UNDEFINED"
    | "PAYMENT_STATUS_CREATED"
    | "PAYMENT_STATUS_CANCELED"
    | "PAYMENT_STATUS_REJECTED"
    | "PAYMENT_STATUS_SUCCESSFUL";
  rajaPriceDetail: {
    /** Format: uint64 */
    count?: string;
    tariff?: definitions["rajaTariff"];
    /** Format: uint64 */
    price?: string;
    /** Format: uint64 */
    totalPrice?: string;
  };
  rajaPriceDetailResponse: {
    /** Format: uint64 */
    totalPrice?: string;
    priceDetail?: definitions["rajaPriceDetail"][];
  };
  rajaRefundPolicyItem: {
    text?: string;
    /** Format: int64 */
    percent?: number;
  };
  /**
   * @default REFUND_STATUS_UNDEFINED
   * @enum {string}
   */
  rajaRefundStatus:
    | "REFUND_STATUS_UNDEFINED"
    | "REFUND_STATUS_REQUESTED"
    | "REFUND_STATUS_FAILED"
    | "REFUND_STATUS_REJECTED"
    | "REFUND_STATUS_SUCCESSFUL"
    | "REFUND_STATUS_PAYMENT_SUCCESSFUL"
    | "REFUND_STATUS_PAYMENT_FAILED"
    | "REFUND_STATUS_PAYMENT_PENDING";
  rajaRefundStatuses: {
    label?: string;
    value?: definitions["rajaRefundStatus"];
  };
  rajaRequestedTrain: {
    trainId?: string;
    wantCompartment?: boolean;
  };
  rajaReserveResponse: {
    /** Format: int64 */
    validUntil?: string;
  };
  rajaSelectedOptionalService: {
    passengerId?: string;
    optionalServiceId?: string;
    freeOptionalServiceId?: string[];
  };
  rajaSelectedOptionalServicePerLeg: {
    trainId?: string;
    selectedOptionalServices?: definitions["rajaSelectedOptionalService"][];
  };
  rajaSessionRequest: {
    wantNew?: boolean;
  };
  rajaSessionResponse: {
    sessionId?: string;
    serviceSessionId?: string;
  };
  rajaStation: {
    name?: string;
    enterTime?: string;
  };
  rajaStationInfo: {
    code?: string;
    farsiName?: string;
    englishName?: string;
  };
  rajaStationSearchResponse: {
    stations?: definitions["rajaStationInfo"][];
  };
  rajaStr: {
    departure?: string;
    return?: string;
  };
  rajaSubmitRefundResponse: {
    refundAmount?: string;
    message?: string;
  };
  /**
   * @default TARIFF_UNSPECIFIED
   * @enum {string}
   */
  rajaTariff:
    | "TARIFF_UNSPECIFIED"
    | "TARIFF_ADULT"
    | "TARIFF_CHILD"
    | "TARIFF_EMPTY"
    | "TARIFF_INFANT"
    | "TARIFF_ADULT_FOREIGN"
    | "TARIFF_CHILD_FOREIGN"
    | "TARIFF_INFANT_FOREIGN";
  /**
   * @default TICKET_STATUS_UNDEFINED
   * @enum {string}
   */
  rajaTicketStatus:
    | "TICKET_STATUS_UNDEFINED"
    | "TICKET_STATUS_INITED"
    | "TICKET_STATUS_ISSUED"
    | "TICKET_STATUS_REFUND_REQUESTED"
    | "TICKET_STATUS_REFUND_ACCEPTED"
    | "TICKET_STATUS_REFUND_NOT_ACCEPTED"
    | "TICKET_STATUS_REFUND_FAILED"
    | "TICKET_STATUS_REFUND_PENDING";
  rajaTrainInfo: {
    trainId?: string;
    trainNumber?: string;
    /** Format: int64 */
    departureDate?: string;
    /** Format: int64 */
    arrivalDate?: string;
    hasCompartment?: boolean;
    wagonType?: definitions["rajaWagonType"];
    /** Format: int64 */
    fare?: string;
    wagonCode?: string;
    wagonName?: string;
    /** Format: int64 */
    compartmentCapacity?: number;
    /** Format: int64 */
    availableSeatCount?: number;
    logoUrl?: string;
    originName?: string;
    destinationName?: string;
    trainOptions?: definitions["rajaTrainOption"][];
    refundPolicy?: definitions["rajaRefundPolicyItem"][];
    companyName?: string;
    priceDetail?: definitions["rajaPriceDetail"][];
    trackingId?: string;
    /** Format: int64 */
    fullPrice?: string;
    /** Format: int64 */
    discountPercent?: string;
    departureDateString?: string;
    departureDateHourString?: string;
    arrivalDateString?: string;
    arrivalDateHourString?: string;
    isInternational?: boolean;
  };
  rajaTrainList: {
    trainList?: definitions["rajaTrainInfo"][];
    calendarData?: definitions["rajaCalenderData"][];
    isCapacityFull?: boolean;
  };
  rajaTrainListQuery: {
    originCode?: string;
    destinationCode?: string;
    passengerCount?: definitions["rajaPassengerCount"];
    /** Format: int64 */
    departureDate?: string;
    wantCompartment?: boolean;
    compartmentGenderType?: definitions["rajaCompartmentGenderType"];
  };
  rajaTrainOption: {
    text?: string;
    code?: string;
    iconUrl?: string;
  };
  rajaTrainTicket: {
    id?: string;
    ticketStatus?: definitions["rajaTicketStatus"];
    /** Format: uint64 */
    price?: string;
    passenger?: definitions["rajaPassenger"];
    /** Format: int64 */
    issueDate?: string;
    tariff?: definitions["rajaTariff"];
    seatNumber?: string;
    compartmentNumber?: string;
    wagonNumber?: string;
    option?: definitions["rajaOptionalService"][];
    freeOption?: definitions["rajaOptionalService"][];
    ticketNumber?: string;
    ticketSeries?: string;
    penaltyAmount?: string;
    penaltyPercentage?: string;
    refundAmount?: string;
    persianStatus?: string;
    /** Format: uint64 */
    totalPrice?: string;
    trainId?: string;
  };
  rajaTrainTrip: {
    id?: string;
    trainInfo?: definitions["rajaTrainInfo"];
    tickets?: definitions["rajaTrainTicket"][];
    wantCompartment?: boolean;
    compartmentType?: definitions["rajaCompartmentGenderType"];
  };
  /** Request message for CAPTCHA verification */
  rajaVerifyCaptchaRequest: {
    captchaToken?: string;
  };
  /**
   * @default WAGON_TYPE_UNDEFINED
   * @enum {string}
   */
  rajaWagonType:
    | "WAGON_TYPE_UNDEFINED"
    | "WAGON_TYPE_COMPARTMENT_4"
    | "WAGON_TYPE_COMPARTMENT_6"
    | "WAGON_TYPE_BUS_4"
    | "WAGON_TYPE_BUS_6";
  rpcStatus: {
    /** Format: int32 */
    code?: number;
    message?: string;
    details?: definitions["protobufAny"][];
  };
}

export interface operations {
  Train_AddFrequentCity: {
    parameters: {
      body: {
        body: definitions["rajaFrequentCity"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_DeleteFrequentCity: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        code?: string;
        rank?: number;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetOrders: {
    parameters: {
      body: {
        body: definitions["rajaAdminGetOrdersRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAdminGetOrdersResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAdminGetOrderResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetPassengers: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAdminGetPassengersResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetPayment: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaOrderPayment"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetTicket: {
    parameters: {
      path: {
        orderId: string;
        status:
          | "ORDER_STATUS_UNDEFINED"
          | "ORDER_STATUS_ORDER_CREATED"
          | "ORDER_STATUS_ORDER_PASSENGERED"
          | "ORDER_STATUS_ORDER_RESERVED"
          | "ORDER_STATUS_RESERVATION_EXPIRED"
          | "ORDER_STATUS_PAYMENT_SUCCESS"
          | "ORDER_STATUS_BUY_FAILED"
          | "ORDER_STATUS_BUY_PENDING"
          | "ORDER_STATUS_BUY_CONFIRMED"
          | "ORDER_STATUS_BUY_PARTIALLED"
          | "ORDER_STATUS_RESERVE_FAILED";
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetTicketPdfResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetTrains: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAdminGetTrainsResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetOrderStatus: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetOrderStatusResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminCalculateRefundPenalty: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
      body: {
        body: definitions["AdminAdminCalculateRefundPenaltyBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaCalculateRefundPenaltyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminSubmitRefund: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
      body: {
        body: definitions["AdminAdminSubmitRefundBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaSubmitRefundResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetProviderNames: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetProviderNamesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminRRList: {
    parameters: {
      body: {
        body: definitions["rajaAdminRRRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAdminRRResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetRRStatus: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetRefundStatusResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Admin_AdminGetTicketsPdf: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetTicketPdfResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetAlert: {
    parameters: {
      query: {
        /** Required */
        originCode?: string;
        /** Required */
        destinationCode?: string;
        /** Required */
        departureDate?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetAlertResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_CreateAlert: {
    parameters: {
      body: {
        body: definitions["rajaAlertRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAlertResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_UpdateAlert: {
    parameters: {
      body: {
        body: definitions["rajaAlertRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaAlertResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetCalenderData: {
    parameters: {
      query: {
        originCode?: string;
        destinationCode?: string;
        departureDate?: string;
        calendarType?: "PERSIAN" | "GREGORIAN";
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetCalenderDataResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_VerifyCaptcha: {
    parameters: {
      body: {
        body: definitions["rajaVerifyCaptchaRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetCaptcha: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetCaptchaResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetError: {
    parameters: {
      path: {
        errorCode: number;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaErrorCodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetFrequentCities: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaStationSearchResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetOrders: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetOrdersResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_CreateOrder: {
    parameters: {
      body: {
        body: definitions["rajaCreateOrderRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaCreateOrderResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetOrderResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_AddPassengers: {
    parameters: {
      path: {
        orderId: string;
      };
      body: {
        body: definitions["TrainAddPassengersBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_UpdateContactInfo: {
    parameters: {
      path: {
        orderId: string;
      };
      body: {
        body: definitions["TrainUpdateContactInfoBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_CreatePayment: {
    parameters: {
      path: {
        orderId: string;
      };
      body: {
        body: definitions["TrainCreatePaymentBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaCreatePaymentResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_SetPassengersOptionalService: {
    parameters: {
      path: {
        orderId: string;
      };
      body: {
        body: definitions["TrainSetPassengersOptionalServiceBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_Reserve: {
    parameters: {
      path: {
        orderId: string;
      };
      body: {
        body: definitions["TrainReserveBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaReserveResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_CalculateRefundPenalty: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
      body: {
        body: definitions["TrainCalculateRefundPenaltyBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaCalculateRefundPenaltyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_SetPassengersOptionalServicePerLeg: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
      body: {
        body: definitions["TrainSetPassengersOptionalServicePerLegBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_Refund: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["apirajaRefundResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_SubmitRefund: {
    parameters: {
      path: {
        orderId: string;
        trainId: string;
      };
      body: {
        body: definitions["TrainSubmitRefundBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaSubmitRefundResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Session_GetSession: {
    parameters: {
      body: {
        body: definitions["rajaSessionRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaSessionResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetStations: {
    parameters: {
      query: {
        query?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaStationSearchResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetAllStations: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaStationSearchResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetTicketsPdf: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetTicketPdfResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetTrainList: {
    parameters: {
      body: {
        body: definitions["rajaGetTrainListRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetTrainListResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetFreeOptionalServices: {
    parameters: {
      path: {
        trainId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetFreeOptionalServicesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetIntermediateStations: {
    parameters: {
      path: {
        trainId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaIntermediateStationsResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetOptionalServices: {
    parameters: {
      path: {
        trainId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetOptionalServicesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetPriceDetail: {
    parameters: {
      path: {
        trainId: string;
      };
      body: {
        body: definitions["TrainGetPriceDetailBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaPriceDetailResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_GetOrderV2: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaGetOrderResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Train_CreatePaymentWithCaptcha: {
    parameters: {
      path: {
        /** Required for OpenAPI path parameter mapping */
        orderId: string;
      };
      body: {
        body: definitions["TrainCreatePaymentWithCaptchaBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["rajaCreatePaymentResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
}

export interface external {}
