/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/countries": {
    get: operations["Routing_GetCountries"];
  };
  "/v1/countries/{CountyName}/cities": {
    get: operations["Routing_GetCities"];
  };
}

export interface definitions {
  flightCities: {
    Name?: string;
    NameFa?: string;
  };
  flightCityResponse: {
    /** Format: int32 */
    code?: number;
    data?: definitions["flightCities"][];
  };
  flightCountries: {
    Name?: string;
    NameFa?: string;
  };
  flightCountryResponse: {
    /** Format: int32 */
    code?: number;
    data?: definitions["flightCountries"][];
  };
  protobufAny: {
    "@type"?: string;
  } & { [key: string]: unknown };
  rpcStatus: {
    /** Format: int32 */
    code?: number;
    message?: string;
    details?: definitions["protobufAny"][];
  };
}

export interface operations {
  Routing_GetCountries: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["flightCountryResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  Routing_GetCities: {
    parameters: {
      path: {
        CountyName: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["flightCityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
}

export interface external {}
