const constants = {
  root: process.env.NEXT_PUBLIC_BASE_URL,
  IMAGE_DOMAIN: process.env.NEXT_PUBLIC_IMAGES_DOMAIN,
  GET_UUID: 'domestic-flight-aggregator/v1/domesticflights/prepare',
  GET_DOMESTIC_TICKET: 'domestic-flight-aggregator/v1/domesticflights',
  FLIGHT_ALERT: 'domestic-flight-aggregator/v1/domesticflight/alert',
  DOMESTIC_FLIGHT: 'domestic-flight-aggregator/v1/domesticflight',
  GET_AIRPORTS: 'domestic-flight-aggregator/v1/airports',
  PASSENGERS: 'passenger/v1/passenger',
  PASSENGERS_V2: 'passenger/v2/passenger',
  ORDERS: 'shoppingorder/v1/orders',
  ORDERSV2: 'shoppingorder/v2/orders',
  ORDERS2: 'shoppingorder/v1/orders2',
  GET_COUNTRIES: 'routing/v1/countries',
  GET_COUNTRIES_V2: 'passenger/v2/countries',
  CREATE_PAYMENT_ORDER: 'payment/v1/product/order',
  CREATE_WALLET_ORDER: 'payment/v1/product/wallet/order',
  GET_ORDER_STATUS: 'payment/v1/product/order',
  GET_ORDER_RECEIPT: 'payment/v2/product/receipt',
  GET_ORDER_INVOICE: 'payment/v2/product/invoice',
  AUTH_REGISTER: 'authserver/register',
  AUTH_TOKEN: 'authserver/token',
  AUTH_LOGIN: 'authserver/login',
  DOWNLOAD: 'shoppingorder/v1/orders',
  REFUND: 'v1/orders',
  ZERO_REFUND: 'shoppingorder/v1/packages/zero-refund',
  GATEWAYS: 'payment/v1/product/gateway',
  GET_TRIPS: 'trips/v2/trips',
  SEND_DOWNLOAD_LINK: '/usermanager/v1/website/application/otp',
  GET_BUSIEST_TRANSPORT_SERVICE_PROVIDERS: 'domestic-flight-aggregator/v1/frequentcities',
  GET_CALENDAR_EVENTS: 'usermanager/v1/calendar',
  GET_DAYS_PRICES: 'domestic-flight-aggregator/v1/calendar',
  FLIGHTS: {
    ORDER_DISCOUNT: (orderId: string) => `/shoppingorder/v1/orders/${orderId}/discount`,
  },
  TRAIN: {
    GET_TRAIN_STATIONS: 'rajatrain/v1/stations',
    GET_TRAIN: 'rajatrain/v1/trains',
    GET_TRAIN_TICKET: 'rajatrain/v1/trains/list',
    GET_TRAIN_ORDERS: 'rajatrain/v1/orders',
    GET_TRAIN_ORDERS_V2: 'rajatrain/v2/orders',
    PASSENGER_SERVICE: 'passenger-services',
    ADD_TRAIN_ORDER_PASSENGER: 'addpassengers',
    IMAGE_DOMAIN: 'https://cdn.780.team/dl/train/',
    DOWNLOAD: 'rajatrain/v1/ticketpdf',
    GET_BUSIEST_TRANSPORT_SERVICE_PROVIDERS: 'rajatrain/v1/frequentcities',
    GET_DAYS_PRICES: 'rajatrain/v1/calendar',
    CAPTCHA: {
      GET_IMAGE: (orderId: string) => `rajatrain/v1/captcha/${orderId}`,
      VERIFY: 'rajatrain/v1/captcha/verify',
    },
    ALERT: 'rajatrain/v1/alert',
    CREATE_PAYMENT: (orderId: string) => `rajatrain/v2/orders/${orderId}/createpayment`,
    CALCULATE_REFUND_PENALTY: (orderId: string, trainId: string) =>
      `rajatrain/v1/orders/${orderId}/trains/${trainId}/calculate-refund-penalty`,
    REFUND: (orderId: string, trainId: string) =>
      `rajatrain/v1/orders/${orderId}/trains/${trainId}/refund-actions`,
  },
  BUS: {
    GET_BUS_STATIONS: 'bus/v1/stations',
    GET_UUID: 'bus/v1/prepare',
    GET_BUS_LIST: 'bus/v1/buslist',
    GET_BUS_SEATS: 'bus/v1/seats',
    ADD_BUS_SEATS: (orderId: string) => `bus/v1/order/${orderId}/seats`,
    ADD_BUS_PASSENGERS: (orderId: string) => `bus/v1/order/${orderId}/passengers`,
    CREATE_ORDER: 'bus/v1/createOrder',
    COMPLETE_ORDER: 'bus/v1/completeOrder',
    FREQUENT_CITIES: 'bus/v1/frequentCities',
    GET_BUS_ORDER: 'bus/v1/order',
    DOWNLOAD: 'bus/v1/ticket',
    UPDATE_CONTACT_INFO: 'bus/v1/internalContactInfo',
    RESERVE_TICKET: 'bus/v1/reserve',
    ORDER_DISCOUNT: (orderId?: string) => `bus/v1/order/${orderId}/discount`,
    GET_DAYS_PRICES: 'bus/v1/calendar',
    ALERT: 'bus/v1/alert',
  },
  INTERNATIONALFLIGHT: {
    CALENDAR: '/international-flight/v1/calendar',
    GET_AIRPORTS: '/international-flight/v1/airports',
    GET_BUSIEST_TRANSPORT_SERVICE_PROVIDERS: '/international-flight/v1/airports/popular',
    GET_TICKET: '/international-flight/v1/availability',
    GET_AVAILABILITY_LIST: '/international-flight/v3/availability',
    GET_PREPARE_REQUEST: '/international-flight/v1/availability',
    GET_TICKET_DETAIL: '/international-flight/v1/availability',
    CREATE_ORDER: '/international-flight/v1/orders',
    ORDER_APPLY_REFUND_PACKAGE: `/international-flight/v1/order/apply-package`,
    ORDER_REMOVE_REFUND_PACKAGE: `/international-flight/v1/order/remove-package`,
    CREATE_ORDER_V2: '/international-flight/v2/orders',
    REFUND: '/international-flight/v1/refund-requests',
    ORDER_DISCOUNT: (orderId?: string) => `/international-flight/v1/order/${orderId}/discount`,
    GET_ORDER_FOR_REFUND: '/international-flight/v1/get-order-for-refund',
    CONFIRM_REFUND: '/international-flight/v1/confirm-refund',
  },
  HOTEL: {
    GET_CITIES_AND_HOTELS: '/hotel/v2/GetCityHotel',
    GET_UUID: 'hotel/v1/search/prepare',
    GET_HOTELS: 'hotel/v2/search',
    GET_HOTELS_SERVERSIDE: 'v1/search',
    GET_FREQUENT_TARGETS: 'hotel/v1/frequentCities',
    GET_PASSENGERS_CONFIG: '/hotel/v1/Configs',
    GET_ORDER: 'hotel/v1/order',
    CONTACT_INFO: 'hotel/v1/ContactInfo',
    GET_SIMILAR_HOTELS: 'hotel/v1/search',
    ORDER_DISCOUNT: (orderId?: string) => `hotel/v1/order/${orderId}/discount`,
    GET_PENALTY: (orderId?: string) => `hotel/v1/order/${orderId}/penalty`,
    REVIEW: 'hotel/v1/search',
    GET_COMMENT: (orderId?: string) => `hotel/v1/order/${orderId}/review`,
    ADD_COMMENT: (orderId?: string) => `hotel/v1/order/${orderId}/review`,
  },

  CMS: {
    GET_FLIGHT_CONTENTS:
      'api/flight-contents?populate=cover,more_info.cover,faq,meta_seo.metaOgSocial.image,meta_seo.twitter.image',
    GET_INT_FLIGHT_CONTENTS:
      'api/international-flight-contents?populate=cover,more_info.cover,faq,meta_seo.twitter.image,meta_seo.metaOgSocial.image',
    GET_TRAIN_CONTENTS:
      'api/train-landing-ctas?populate=cover,more_info.cover,faq,meta_seo.metaOgSocial.image,meta_seo.twitter.image',
    GET_BUS_CONTENTS:
      'api/bus-landing-ctas?populate=cover,more_info.cover,faq,meta_seo.metaOgSocial.image,meta_seo.twitter.image',
    GET_HOTEL_CONTENTS:
      'api/hotel-cta?populate=cover,more_info.cover,faq,meta_seo.twitter.image,meta_seo.metaOgSocial.image',
    GET_TOURISM_LANDING_CONTENTS:
      'api/home-tourism-landing-cta?populate=cover,more_info.cover,faq,meta_seo.metaOgSocial.image,meta_seo.twitter.image',
    GET_TRAIN_SINGLE_PAGE_CONTENTS:
      'api/one-way-train-contents?populate=*&filters[yata_code][code][$eq]=',
  },
  TOUR: {
    GET_ORDER: '/tour/v1/vouchers',
    GET_PROMOTION_SLIDER: '/campaign/v1/banner/global?page=tour_landing',
    GET_HOT_TOURS: '/tour/v2/trips',
    GET_TOUR_DETAIL: '/tour/v2/pdp',
    GET_CITIES: '/tour/v2/zones',
    GET_SUGGESTION: '/tour/v2/trips/suggestions',
    GET_SEARCH_ITEMS: '/tour/v2/search',
    GET_CHECK_OUT: '/tour/v2/checkout',
  },
  PAYMENT: {
    GET_BANNER: 'campaign/v1/banner/global',
  },
  SSO_LOGIN: {
    GET_AUTH_TOKEN: 'authserver/web_token',
    SSO_VALIDATION: 'authserver/introspect',
    GET_HOT_TOURS: '/tour/v1/trips',
  },
};

export default constants;
