export const stationLatinToFarsiHead: { [key: string]: string } = {
  abadan: 'آبادان',
  abadeh: 'آباده',
  abali: 'آبعلی',
  abarkuh: 'ابرکوه',
  abbasabad: 'عباس آباد',
  abhar: 'ابهر',
  'abu musa': 'ابوموسی',
  abyek: 'آبیک',
  ahar: 'اهر',
  ahvaz1: 'اهواز',
  ahvaz2: 'اهواز',
  ahvaz3: 'اهواز',
  ajab_shir: 'عجب شیر',
  alborz: 'البرز',
  aliabad: 'علی آباد',
  aligoodarz: 'الیگودرز',
  amol: 'آمل',
  andimeshk: 'اندیمشک',
  andisheh: 'اندیشه',
  ankara: 'آنکارا',
  antakya: 'انطاکیه',
  antalya: 'آنتالیا',
  'aq baba': 'آق بابا',
  aradan: 'آرادان',
  arak: 'اراک',
  arasenj: 'آراسنج',
  ardabil: 'اردبیل ',
  ardakan: 'اردکان',
  ardal: 'اردل',
  asadabad: 'اسدآباد',
  asaluyeh: 'عسلویه',
  ashkhaneh: 'آشخانه',
  ashtiyan: 'آشتیان',
  astanehyeashrafiyeh: 'آستانه اشرفیه',
  astara: 'آستارا',
  avaj: 'آوج',
  azadshahr: 'آزادشهر',
  azarshahr: 'آذرشهر',
  azna: 'ازنا',
  babol: 'بابل',
  babolsar: 'بابلسر',
  badreh: 'بدره ',
  bafgh: 'بافق',
  baft: 'بافت',
  baghdad: 'بغداد',
  bajestan: 'بجستان',
  baku: 'باکو',
  bam: 'بام',
  'bandar abbas': 'بندرعباس',
  'bandar lengeh': 'بندرلنگه',
  'bandar_e gaz': 'بندر گز',
  bandarturkmen: 'بندر ترکمن',
  bandareanzali: 'بندرانزلی',
  baneh: 'بانه',
  bardaskan: 'برداسکن',
  bashravie: 'بشرویه',
  basre: 'بصره',
  bastak: 'بستک',
  batumi: 'باتومی',
  behbahan: 'بهبهان',
  behshahr: 'بهشهر',
  biarejamand: 'بیارجمند',
  bijar: 'بیجار',
  birjand: 'بیرجند',
  'boein zahra': 'بویین زهرا',
  bojnurd: 'بجنورد',
  boroujen: 'بروجن',
  boroujerd: 'بروجرد',
  bukan: 'بوکان',
  bushehr: 'بوشهر',
  chabahar: 'چابهار',
  chalus: 'چالوس',
  damavand: 'دماوند',
  damghan: 'دامغان',
  darab: 'داراب',
  daran: 'داران',
  dargahan: 'درگهان',
  dargaz: 'درگز',
  darmian: 'درمیان',
  dashtabi: 'دشتابی',
  dashtestan: 'دشستان',
  dashti: 'دشتی',
  dehdasht: 'دهدشت',
  dehgolan: 'دهگلان',
  delijan: 'دلیجان',
  dena: 'دنا',
  deylam: 'دیلم',
  dezful: 'دزفول',
  dir: 'دیر',
  divandarreh: 'دیوان دره',
  dorud: 'دورود',
  eejrud: 'ایجرود',
  erbil: 'اربیل',
  erzurum: 'ارزروم',
  esfahan: 'اصفهان',
  isfahan: 'اصفهان',
  esfarayen: 'اسفراین',
  eshtehard: 'اشتهارد ',
  'eslamabad_e gharb': 'اسلام آباد غرب',
  eslamshahr: 'اسلام شهر',
  eyvanekey: 'ایوانکی',
  farmahin: 'فرمهین',
  farooj: 'فاروج',
  farsan: 'فارسان',
  ferdos: 'فردوس',
  fereydunkenar: 'فریدونکنار',
  firuzkuh: 'فیروزکوه',
  'foolad shahr': 'فولاد شهر',
  fuman: 'فومن',
  gachsaran: 'گچساران',
  garash: 'گراش',
  garmi: 'گرمی',
  garmsar: 'گرمسار',
  'ghaleh ganj': 'قلعه گنج',
  'gilane gharb': 'گیلانغرب',
  golpayegan: 'گلپایگان',
  gonabad1: 'گناباد',
  gonabad2: 'گناباد',
  gonaveh: 'گناوه',
  gonbadekavus: 'گنبدکاووس',
  gorgan: 'گرگان',
  'hadi shahr': 'هادیشهر',
  hamadan: 'همدان',
  hashtgerd1: 'هشتگرد',
  hashtgerd2: 'هشتگرد',
  hashtpar: 'هشتپر',
  hashtrood: 'هشترود',
  harat: 'هرات',
  heris: 'هریس',
  igdir: 'ايغدير',
  ilam: 'ایلام ',
  'iran shahr': 'ایرانشهر',
  isfahan1: 'اصفهان',
  isfahan2: 'اصفهان',
  isfahan3: 'اصفهان',
  isfahan4: 'اصفهان',
  islamabad: 'اسلام آباد',
  istanbul: 'استانبول',
  ivan: 'ایوان ',
  izeh: 'ایذه',
  jahrom: 'جهرم',
  jajarm: 'جاجرم',
  jame: 'جم',
  jask: 'جاسک',
  javanroud: 'جوانرود',
  jiroft: 'جیرفت',
  jolfa: 'جلفا',
  jowzak: 'جوزک',
  kabudarahang: 'کبودرآهنگ',
  kabul: 'کابل',
  kahnooj: 'کهنوج',
  kamalabad: 'کمال آباد ',
  kamyaran: 'کامیاران',
  kandahar: 'قندهار',
  kangan: 'کنگان',
  karaj: 'کرج',
  karbala: 'کربلا',
  kashan: 'کاشان ',
  kashmar: 'کاشمر',

  kashmar1: 'کاشمر',
  kashmar2: 'کاشمر',
  kazerun: 'کازرون',
  kelachay: 'کلاچای',
  kelardasht: 'کلاردشت',
  kerman: 'کرمان',
  keyar: 'کیار',
  khaf: 'خواف',
  khalkhal: 'خلخال ',
  khash: 'خاش',
  khoansar: 'خوانسار',
  khodabandeh: 'خدابنده',
  khomein: 'خمین',
  'khomeini shahr': 'خمینی شهر ',
  khomeyr: 'خمیر',
  khonj: 'خنج',
  khormoj: 'خورموج',
  khorramabad: 'خرم آباد',
  khorramdarreh: 'خرمدره',
  khorramshahr: 'خرمشهر',
  khosf: 'خوسف',
  khoy: 'خوی',
  kiyashahr: 'کیاشهر',
  konarak: 'کنارک',
  kordkuy: 'کردکوی',
  kouhrang: 'کوهرنگ',
  kuhdasht: 'کوهدشت',
  lahijan: 'لاهیجان',
  lahore: 'لاهور',
  lamerd: 'لامرد',
  langrud: 'لنگرود',
  lar: 'لار',
  lordegan: 'لردگان',
  mahabad: 'مهاباد',
  mahallat: 'محلات',
  mahmoodabad: 'محمودآباد',
  mahneshan: 'ماه نشان',
  mahshahr: 'ماهشهر',
  maku: 'ماکو',
  malard: 'ملارد',
  malayer: 'ملایر',
  malekan: 'ملکان',
  'manjil abad': 'منجیل آباد',
  maragheh: 'مراغه',
  marand: 'مرند',
  marivan: 'مریوان',
  mahriz: 'مهریز',
  marzanabad: 'مرزن آباد',
  masal: 'ماسال',
  mashhad: 'مشهد',
  'masjed soleyman': 'مسجد سلیمان',
  mazarsharif: 'مزارشریف',
  'mehdi shahr': 'مهدی شهر',
  'meshkin dasht': 'مشکین دشت ',
  'meshkin shahr': 'مشکین شهر',
  meybod: 'میبد',
  miameh: 'میامی',
  minab: 'میناب',
  minoodasht: 'مینودشت',
  mobarakeh: 'مبارکه ',
  mosul: 'موصل',
  nahavand: 'نهاوند',
  nain: 'نایین ',
  najaf: 'نجف',
  najafabad: 'نجف آباد',
  nakhchivan: 'نخجوان',
  namin: 'نمین ',
  nasimshahr: 'نسیم شهر',
  nazarabad1: 'نظرآباد',
  nazrabad2: 'نظر آباد',
  nazarabad: 'نظر آباد',

  nehbandan: 'نهبندان',
  neka: 'نکا',
  neyriz: 'نی ریز',
  neyshabur: 'نیشابور',
  'nik shahr': 'نیک شهر',
  nir: 'نیر',
  nourabad: 'نورآباد',
  nowshahr: 'نوشهر',
  nurabad: 'نورآباد',
  parsabad: 'پارس آباد ',
  parsian: 'پارسیان',
  paveh: 'پاوه',
  piranshahr: 'پیرانشهر',
  poldokhtar: 'پلدختر',
  polur: 'پلور',
  qaemshahr: 'قائمشهر',
  qarchak: 'قرچک',
  'qasr_e shirin': 'قصر شیرین',
  qayen_ghayenat_ghayen: 'قاین / قائنات / قائن',
  qazvin: 'قزوین',
  qeshm: 'قشم',
  qom: 'قم',
  'qom_fadak terminal': 'قم - پایانه فدک',
  qorveh: 'قروه',
  quchan: 'قوچان',

  quchan1: 'قوچان',
  quchan2: 'قوچان',
  rafsanjan: 'رفسنجان',
  rahimabad: 'رحیم آباد',
  ramand: 'رامند',
  ramhormoz: 'رامهرمز',
  ramian: 'رامیان',
  ramsar: 'رامسر',
  rasht: 'رشت',
  ravar: 'راور',
  razan: 'رزن',
  rouyin: 'رویان',
  rudbar: 'رودبار',

  rudbar1: 'رودبار',
  rudbar2: 'رودبار',
  rudehen: 'رودهن',
  rudsar: 'رودسر',
  sabzevar: 'سبزوار',

  sabzevar1: 'سبزوار',
  sabzevar2: 'سبزوار',
  salafchegan: 'سلفچگان',
  'salman shahr': 'سلمانشهر',
  salmas: 'سلماس',
  samaneh: 'سامان',
  samarra: 'سامرا',
  samirom: 'سمیرم ',
  sanandaj: 'سنندج',
  saqqez: 'سقز',
  sarab: 'سراب',
  sarakheh: 'سرخه',
  sarakhs: 'سرخس',
  saravan: 'سراوان',
  sarayan: 'سرایان',
  sarbaz: 'سرباز',
  sarbisheh: 'سربیشه',
  sarcham: 'سرچم',
  sardasht: 'سردشت',
  sari: 'ساری',
  sarkhak: 'سرخرود',
  sarpolezahab: 'سرپل ذهاب',
  saveh: 'ساوه',
  'savoj bolaq': 'ساوج بلاغ ',
  semnan: 'سمنان',
  shabestar: 'شبستر',
  'shahin dezh': 'شاهین دژ',
  'shahin shahr': 'شاهین شهر ',
  shahrak: 'شهرک',
  'shahr_e babak': 'شهر بابک',
  shahreghods: 'شهر قدس',
  shahrekord: 'شهرکرد',
  shahrreza: 'سشهرضا ',
  shahriar: 'شهریار',
  shahroud: 'شاهرود',
  shalamcheh: 'شلمچه',
  shalman: 'شلمان',
  shendabad: 'شندآباد',
  shiraz: 'شیراز',
  shiraz1: 'شیراز',
  shiraz2: 'شیراز',
  shiraz3: 'شیراز',
  shiraz4: 'شیراز',
  shirud: 'شیرود',
  shirvan: 'شیروان',
  shush: 'شوش',
  shushtar: 'شوشتر',
  siahkal: 'سیاهکل',
  sirjan: 'سیرجان',
  soltanabad: 'سلطان آباد',
  soomaresara: 'صومعه سرا',
  sulaymaniyah: 'سلیمانیه',
  tabas: 'طبس',
  tabriz1: 'تبریز',
  tabriz2: 'طرابوزان',
  tafresh: 'تفرش',
  taft: 'تفت',
  takab: 'تکاب',
  takestan: 'تاکستان',
  taleqan: 'طالقان ',
  tangestan: 'تنگستان',
  tarom: 'طارم',
  taybad: 'تایباد',
  tbilisi: 'تفلیس',
  tehran: 'تهران',
  tehran1: 'تهران',
  tehran2: 'تهران',
  tehran3: 'تهران',
  tehran4: 'تهران',
  tehran5: 'تهران',
  tehran6: 'تهران',
  tonekabon: 'تنکابن',
  torbatheydariyeh: 'تربت حیدریه',
  torbatjam: 'تربت جام',
  tuyserkan: 'تویسرکان',
  urmia: 'ارومیه',
  van: 'وان',
  varezneh: 'ورزنه',
  yasuj: 'یاسوج',
  yazd: 'یزد',
  yerevan: 'ایروان',
  zabol: 'زابل',
  zahak: 'زهک',
  zahedan: 'زاهدان',
  zanjan: 'زنجان',
  'zarin shahr': 'زرین شهر ',
  zarinabad: 'زرین آباد',
  ghidar: 'قیدار',
  kermanshah: 'کرمانشاه',
  amlash: 'املش',
};
